fruits=["apple","banana","cherry"]
print("Original list:",fruits)
fruits.append("orange")
print("After append:",fruits)
fruits.insert(2,"kiwi")
print("After insert: ",fruits)
fruits.sort()
print(fruits)
fruits.extend([3,4,3])
print("After extend: ",fruits)
fruits.pop(3)
print("after pop",fruits)
fruits.remove(3)
print(fruits)
count_1=fruits.count("banana")
print(count_1)
fruits.clear()
print(fruits)